/**
 * Helper client functions for Swiggy OAuth & MCP service interactions via backend
 */

export interface SwiggyStatusResponse {
  connected: boolean;
  expiresAt?: string;
  scope?: string;
}

/**
 * Initiate Swiggy OAuth 2.1 PKCE Flow
 * Fetches authorization URL generated by backend and redirects browser
 */
export async function initiateSwiggyOAuth(): Promise<void> {
  try {
    const res = await fetch("/api/swiggy/auth/start");
    if (!res.ok) {
      const err = await res.json().catch(() => ({}));
      throw new Error(err.error || `Server returned ${res.status}`);
    }

    const data = await res.json();
    if (data.authorizeUrl) {
      window.location.href = data.authorizeUrl;
    } else {
      throw new Error("No authorization URL returned from backend");
    }
  } catch (err: any) {
    console.error("[Swiggy Auth] Failed to initiate Swiggy OAuth:", err);
    throw err;
  }
}

/**
 * Check if the user has an active, authenticated Swiggy connection in DB
 */
export async function getSwiggyStatus(): Promise<SwiggyStatusResponse> {
  try {
    const res = await fetch("/api/swiggy/status");
    if (!res.ok) {
      return { connected: false };
    }
    return await res.json();
  } catch (err) {
    console.error("[Swiggy Auth] Error checking Swiggy status:", err);
    return { connected: false };
  }
}

/**
 * Disconnect user's Swiggy account
 */
export async function disconnectSwiggyAccount(): Promise<boolean> {
  try {
    const res = await fetch("/api/swiggy/disconnect", { method: "POST" });
    if (!res.ok) {
      throw new Error("Failed to disconnect Swiggy");
    }
    return true;
  } catch (err) {
    console.error("[Swiggy Auth] Error disconnecting Swiggy:", err);
    return false;
  }
}

/**
 * Execute an MCP Tool call via NutriFlow backend
 */
export async function callSwiggyMcpTool(
  server: "food" | "im" | "dineout",
  toolName: string,
  toolArgs: Record<string, any> = {}
): Promise<any> {
  const res = await fetch(`/api/swiggy/tools/${server}/${encodeURIComponent(toolName)}`, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify(toolArgs),
  });

  if (!res.ok) {
    const errorData = await res.json().catch(() => ({}));
    throw new Error(errorData.error || `MCP tool execution failed (${res.status})`);
  }

  return await res.json();
}
